# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: Technical Blog
email: ineedanavailableemail@gmail.com
name: helltrain
description: >- # this means to ignore newlines until "baseurl:"
  All things security and some misc stuff
keywords: [offensive,malware,systems,networks]
baseurl: '' # the subpath of your site, e.g. /`blog
url: 'https://helltra.in' # the base hostname & protocol for your site, e.g. http://example.com
domain: 'helltra.in' # the domain name for your site, e.g. example.com
language: en
analytics: # the Google Analytics property ID, e.g. UA-XXXXX-Y TODO

comments: false # enable comments
disqus: # disqus account

mathjax: true # Math support
diagram: false # Diagrams support

paginate: 25
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
        sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Build settings
markdown: kramdown
plugins:
  - github-pages
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
